### PR TITLE
Added board flag properties to comment props list

### PR DESCRIPTION
**Pull request by catamphetamine**
You have added new properties but you have done it without updating the comment props list.

### CODE REVIEW

**Comment by desuwa** [comment]
Thanks!
Before I merge this, can you remove the `2 character string` part please? The new flag codes are 3 characters long for example and there probably won't be a character limit for this field.

**Comment by catamphetamine** [comment]
> The new flag codes are 3 characters long

You mean new "troll" flags or you're transitioning from `ISO 3166-1 alpha-2` to `ISO 3166-1 alpha-3` for country flags?

**Comment by catamphetamine** [comment]
> can you remove the 2 character string part

Should I put `any string` there?

**Comment by desuwa** [comment]
> Should I put any string there?

Sure. Or leave it blank if you want.

> You mean new "troll" flags.

Yes. Some of the new flags we added have a 3 characters long code.

**Comment by catamphetamine** [comment]
Cool.
Corrected.

**Pull request merged**
