### PR TITLE
Refactor documentation

### PR DESCRIPTION
**Pull request by cyggy**
This is a proposed refactor of the API documentation. Some of the formatting has been cleaned up and each route was given its own page, `boards.json` and its attributes were also documented. 
 
If anyone has feedback, if you like/hate the changes, have recommendations, plz chime in. It still needs to be proofread for spelling errors and other dumb mistakes.

### CODE REVIEW

**Comment by AGSPhoenix** [comment]
The `m_img` attribute discussed in #63 is not mentioned.

**Comment by cyggy** [comment]
missing `unique_ips`

**Comment by cyggy** [comment]
Ready for review & merge

**Comment by dcdholder** [comment]
Nice work on this.

Check #71 and #45 for info on last_modified (it's updated on thread/post edit events, as well as additions and deletions). last_modified should also not have a row in Threads.md, and it's not in the example output.

**Comment by cyggy** [comment]
@dcdholder thanks! removed it

**Comment by saxamaphone69** [comment]
Nice work, @cyggy

**Comment by catamphetamine** [comment]
@cyggy Oh wow, this is now better than [my reverse-engineered docs](https://github.com/catamphetamine/imageboard/blob/master/docs/engines/4chan.md)

**Pull request merged**
